version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./reports:/app/reports
    depends_on:
      - chroma

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - ./data/chroma:/chroma/chroma
    ports:
      - "8001:8000"
